/** @type {import('prettier').Config} */
module.exports = {
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^@/styles/(.*)$",
    "^@undrstnd/ui/styles/globals.css$",
    "",
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "^@undrstnd/(?!ui(?:/lib(?:/fonts)?)?$)(.*)$",
    "",
    "^types$",
    "^@/env(.*)$",
    "^@/types/(.*)$",
    "^@/types$",
    "",
    "^@/config/(.*)$",
    "^@/hooks/(.*)$",
    "^@/lib/(.*)$",
    "^@undrstnd/ui/lib$",
    "^@undrstnd/ui/lib/fonts$",
    "",
    "^@/components/(.*)$",
    "^@undrstnd/ui$",
    "",
    "@/actions/(.*)",
    "",
    "^[./]",
  ],
  tailwindFunctions: ["clsx", "cn", "twmerge", "cva"],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
}
